=== AaronDinesh/4D2/mySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- This defines all the XML elements needed for a game-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns="local" targetNamespace="local">

    <xsd:simpleType name="monetaryValueType">
        <xsd:restriction base='xsd:decimal'>
            <xsd:fractionDigits value="2"/>
        </xsd:restriction>        
    </xsd:simpleType>
 
    <xsd:complexType name="fullnameType">
        <xsd:sequence>
            <xsd:element name="firstname" type="xsd:string" minOccurs="1"/>
            <xsd:element name="lastname" type="xsd:string" minOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="fullnameExtendedType">
        <xsd:complexContent>
            <xsd:extension base="fullnameType">
                <xsd:sequence>
                    <xsd:element name="middlename" type="xsd:string" minOccurs="1"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="designerName" type="fullnameType"/>
    <xsd:element name="designerNameExtended" type="fullnameExtendedType"/>
    
    <xsd:simpleType name="popularityRatingType">
        <xsd:restriction base='xsd:decimal'>
            <xsd:totalDigits value="2"/>
            <xsd:fractionDigits value="1"/>
            <xsd:minInclusive value="0.0"/>
            <xsd:maxInclusive value="5.0"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="cardInfoType">
        <xsd:restriction base="xsd:decimal">
			<!--Defines the card info type. It will contains the first 4 digits and then the last 4 digits (period seperated) of the card
				used to pay for the game. in XXXX.XXXX-->
            <xsd:totalDigits value="8"/>
            <xsd:fractionDigits value="4"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="emailInfoType">
        <xsd:restriction base="xsd:string">
            <!-- RegExp to assert that an email must be present-->
            <xsd:pattern value="[^@]+@[^\.]+\..+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="paymentType">
        <xsd:choice>
            <xsd:element name="card" type="cardInfoType"/>
            <xsd:element name="paypal" type="emailInfoType"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:simpleType name="ageRatingType">
        <xsd:annotation>
            <xsd:documentation>
                This defines the ERSB rating system for a game. It is as follows:
                    - E    : For everyone
                    - E10+ : For ages 10+
                    - T    : For teens. Generally 13+
                    - M    : For ages 17+
                    - AO   : For adults only. 18+
                    - RP   : Not yet assigned an ESRB rating
                    - RP17+: Not yet assigned an ESRB rating, but it is anticipated to be 17+
                    More information can be found here: https://www.esrb.org/ratings-guide/ 
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="E"/>
            <xsd:enumeration value="E10+"/>
            <xsd:enumeration value="T"/>
            <xsd:enumeration value="M"/>
            <xsd:enumeration value="AO"/>
            <xsd:enumeration value="RP"/>
            <xsd:enumeration value="RP17+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="gameType">
        <xsd:annotation>
            <xsd:documentation>
                This is the base type for a "game" object. Contains:
                    - Title: Name of the game (Type= string)
                - designerName / designerNameExtended: The name of the devs. Can be unlimited. (Type= fullnameType or
                                                       fullnameExtendedType)
                - isIntalled: Is the game installed on the system (Type= Boolean)
                - price: The price of the game (Type= monetaryValueType)
                - esrbRating: The ESRB Rating of the game (Type= ageRatingType)
                - gameRating: The popularity of the game (Type= popularityRatingType)
                - genre: The genre of the game (Type= string)
            </xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="Title" type="xsd:string"/>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element name="designerName" type="fullnameType"/>
                <xsd:element name="designerNameExtended" type="fullnameExtendedType"/>
            </xsd:choice>
            <xsd:element name="isInstalled" type="xsd:boolean"/>
            <xsd:element name="price" type="monetaryValueType"/>
            <xsd:element name="paymentMethod" type="paymentType"/>
            <xsd:element name="esrbRating" type="ageRatingType"/>
            <xsd:element name="gameRating" type="popularityRatingType"/>
            <xsd:element name="genre" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    

    <xsd:complexType name="seriesType">
        <xsd:annotation>
            <xsd:documentation>
                This is a type for a game series. Contains:
                    - seriesTitle: Title of the series. (Type= string)
                    - atomicGame : An instance of a game. Can be unlimited. (Type= gameType) 
            </xsd:documentation>
        </xsd:annotation>

        <xsd:sequence>
            <xsd:element name="Game" type="gameType" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="seriesTitle" type="xsd:string"/>
    </xsd:complexType>
    
    <xsd:complexType name="mediaType">
		<xsd:choice maxOccurs="unbounded">
			<xsd:element name="Game" type="gameType" maxOccurs="unbounded"/>
			<xsd:element name="Series" type="seriesType" maxOccurs="unbounded"/>
		</xsd:choice>
	</xsd:complexType>


    <!-- Below are definable Elements -->
    <xsd:element name="Game" type="gameType"/>
    <xsd:element name="Series" type="seriesType"/>
    
    <xsd:element name="Library">
        <xsd:complexType mixed="true">
            <xsd:annotation>
                <xsd:documentation>
                    This is an element that can store multiple Series and or Games. Think of a Steam Game Library
                </xsd:documentation>
            </xsd:annotation>

            <xsd:sequence>
                <xsd:element name="Owner" type="xsd:string" default="Jane Doe" maxOccurs="1"/>
                <xsd:element name="Media" type="mediaType"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== AaronDinesh/4D2/xmlTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>

<Library xmlns="local" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="local mySchema.xsd">
	
	<Owner>Johnny Phones</Owner>
	
	<Media>
		<Series seriesTitle="Kingdoom" xmlns="local">
			<Game>
				<Title>Kingdoom I</Title>
				<designerName>
					<firstname>Conflict</firstname>
					<lastname>Nerd</lastname>
				</designerName>
				<isInstalled>true</isInstalled>
				<price>69.99</price>
				<paymentMethod>				
					<paypal>johnnyphones@gmail.com</paypal>
				</paymentMethod>
				<esrbRating>T</esrbRating>
				<gameRating>4.5</gameRating>
				<genre>Action-Adventure</genre>
			</Game>
			
			<Game>
				<Title>Kingdoom II: Longsword</Title>
				<designerName>
					<firstname>Conflict</firstname>
					<lastname>Nerd</lastname>
				</designerName>
				<isInstalled>true</isInstalled>
				<price>69.99</price>
				<paymentMethod>
					<card>3060.7653</card>
				</paymentMethod>
				<esrbRating>T</esrbRating>
				<gameRating>3.8</gameRating>
				<genre>Action-Adventure</genre>
			</Game>
			
			<Game>
				<Title>Kingdoom III: Sabre</Title>
				<designerName>
					<firstname>Conflict</firstname>
					<lastname>Nerd</lastname>
				</designerName>
				<isInstalled>false</isInstalled>
				<price>69.99</price>
				<paymentMethod>
					<paypal>johnnyphones@gmail.com</paypal>
				</paymentMethod>
				<esrbRating>T</esrbRating>
				<gameRating>3.8</gameRating>
				<genre>Action-Adventure</genre>
			</Game>
			
			<Game>
				<Title>Kingdoom IV: Excalibur</Title>
				<designerName>
					<firstname>Conflict</firstname>
					<lastname>Nerd</lastname>
				</designerName>
				<isInstalled>false</isInstalled>
				<price>89.99</price>
				<paymentMethod>
					<card>3060.7653</card>
				</paymentMethod>
				<esrbRating>T</esrbRating>
				<gameRating>4.9</gameRating>
				<genre>Action-Adventure</genre>
			</Game>
		</Series>
		
		
		<Game>
			<Title>The Elder Scrolls V:Skyrim</Title>
	
			<designerName>
				<firstname>Todd</firstname>
				<lastname>Howard</lastname>
			</designerName>
	
			<isInstalled>
				true
			</isInstalled>
		
			<price>39.99</price>
			<paymentMethod>
				<paypal>johnnyphones@gmail.com</paypal>
			</paymentMethod>
			<esrbRating>AO</esrbRating>
			
			<gameRating>5.0</gameRating>
			
			<genre>Fantasy</genre>
		
		</Game>
	
		<Game>
			<Title>Shadow Quest</Title>
			<designerNameExtended>
				<firstname>Emily</firstname>
				<lastname>Walker</lastname>
				<middlename>Mary-Jane</middlename>
			</designerNameExtended>
			<isInstalled>false</isInstalled>
			<price>50.99</price>
			<paymentMethod>
				<card>4035.1234</card>
			</paymentMethod>
			<esrbRating>T</esrbRating>
			<gameRating>4.7</gameRating>
			<genre>Action RPG</genre>
		</Game>
	</Media>
</Library>
